variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ''
  GIT_DEPTH: 10
  GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAME

stages:
  - test
  - deploy

job-test:
  image: node:8.15.1-alpine
  stage: test
  script:
    - npm install mocha -g
    - npm test
  tags:
    - devqa90

job-deploy:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  script:
    - grep . /etc/*-release
    - docker build -t server-xsync-api-2.0/node-web-app .
    - docker images
  tags:
    - devqa90
