image: atlassian/default-image:latest
pipelines:
  default:
    - step:
        name: Deploy
        deployment: Test
        script:
          # - pwd
          # - ssh -V
          # - mkdir -p ~/.ssh
          - echo $MY_ACCESS_KEY
          - echo $DEPLOY_SERVER_IP
          - echo $MY_ACCESS_KEY > ./access_key.pem
          - chmod 600 ./access_key.pem
          - chmod 600 ./build/bmm-web.pem
          - ls -alh
          # - docker build -t frontend:latest .
          # - docker save -o frontend.tar frontend:latest
          # - scp frontend.tar ubuntu@52.79.120.204:/home/ubuntu
          - cat ./access_key.pem
          - ssh -i ./build/bmm-web.pem ubuntu@$(echo $DEPLOY_SERVER_IP) 'bash -s' < ./build/docker-run.sh
          - echo 'Deploy success!!!'
        # services:
        #   - docker
# ssh ubuntu@$(echo $DEPLOY_SERVER_IP)
