image: atlassian/default-image:latest
pipelines:
  default:
    - step:
        name: Deploy
        deployment: Test
        script:
          - mkdir -p ~/.ssh
          - (umask  077 ; echo $MY_ACCESS_KEY > ~/.ssh/id_rsa)
          - docker build -t frontend:latest .
          - docker save -o frontend.tar frontend:latest
          - scp frontend.tar ubuntu@52.79.120.204:/home/ubuntu
          - ssh ubuntu@52.79.120.204 'bash -s' <./build/docker-run.sh
          - echo "Deploy step finished"
        services:
          - docker
# ssh ubuntu@$(echo $DEPLOY_SERVER_IP)
