image: atlassian/default-image:latest
pipelines:
  default:
    - step:
        name: Deploy to BMM WEB
        deployment: production
        script:
          - ssh centos@13.209.7.132 'bash -s' < ./build/deploy.sh
          - echo "Deploy step finished"
