image: atlassian/default-image:latest
pipelines:
  default:
    - step:
        name: Deploy
        deployment: Test
        script:
          - docker build -t frontend:latest .
          - docker save -o frontend.tar frontend:latest
          - ssh ubuntu@52.79.120.204
          - ssh ubuntu@52.79.120.204 'bash -s' <./build/docker-run.sh
          - echo "Deploy step finished"
        services:
          - docker
# ssh ubuntu@$(echo $DEPLOY_SERVER_IP)
