image: atlassian/default-image:latest
pipelines:
  default:
    - step:
        name: Deploy
        deployment: test
        script:
          - pwd
          - ssh -V
          - mkdir -p ~/.ssh
          - echo $MY_ACCESS_KEY > ./access_key.pem
          - chmod 400 ./access_key.pem
          - ls -alh
          # - docker build -t frontend:latest .
          # - docker save -o frontend.tar frontend:latest
          # - scp frontend.tar ubuntu@52.79.120.204:/home/ubuntu
          - cat ./access_key.pem
          - ssh -i ./build/bmm-web.pem ubuntu@52.79.120.204 'bash -s' < ./build/docker-run.sh
          - echo 'Deploy success!!!'
        # services:
        #   - docker
# ssh ubuntu@$(echo $DEPLOY_SERVER_IP)
