image: atlassian/default-image:latest
pipelines:
  default:
    - step:
        name: Deploy
        deployment: test
        script:
          - mkdir -p ~/.ssh
          - echo $MY_ACCESS_KEY > access_key.pem
          # - docker build -t frontend:latest .
          # - docker save -o frontend.tar frontend:latest
          # - scp frontend.tar ubuntu@52.79.120.204:/home/ubuntu
          - ssh -i ./access_key.pem ubuntu@52.79.120.204 'bash -s' <./build/docker-run.sh > deploy_result.txt
          - cat deploy_result.txt
        # services:
        #   - docker
# ssh ubuntu@$(echo $DEPLOY_SERVER_IP)
