image: atlassian/default-image:latest
pipelines:
  default:
    - step:
        name: Deploy
        deployment: deployment_docker
        script:
          - printenv
        services:
          - docker
