image: atlassian/default-image:latest
pipelines:
  default:
    - step:
        name: Deploy
        deployment: Test
        script:
          # - printenv
          - echo $DEPLOY_SERVER_IP
          # - docker build -t frontend:latest .
          # - docker save -o frontend.tar frontend:latest
          - ssh ubuntu@$(echo $DEPLOY_SERVER_IP)
          # - ssh ubuntu@$(echo $DEPLOY_SERVER_IP) 'bash -s' <./build/docker-run.sh
          - echo "Deploy step finished"
        services:
          - docker
# ssh ubuntu@$(echo $DEPLOY_SERVER_IP)
