image: atlassian/default-image:latest
pipelines:
  default:
    - step:
        name: Deploy
        deployment: deployment_docker
        script:
          - printenv
          - docker build -t frontend:latest .
          - docker save -o frontend.tar frontend:latest
          - scp -i frontend.tar ubuntu@$DEPLOY_SERVER_IP:/home/ubuntu
          - ssh ubuntu@$DEPLOY_SERVER_IP 'bash -s' <./build/docker-run.sh
          - echo "Deploy step finished"
