version: '0.0'

services:
  nodejs:
    build: .
    dockerfile: ./docker/app
    image: node:8
    container_name: nodejs3001
    restart: unless-stopped
    # env_file: .env
    working_dir: '/app'
    networks:
      - app-network
    ports:
      - '8080:3001'
    volumes:
      - .:/app
      # - ./node_modules:/home/app/node_modules
    # command: yarn dev-live-api
  # redis6001:
  #   image: redis:5.0.3
  #   container_name: redis8754
  #   hostname: redis8754
  #   labels:
  #     - 'name=redis'
  #     - 'mode=standalone'
  #   networks:
  #     - app-network
  #   network_mode: host
  #   ports:
  #     - 8754:6379
  #   volumes:
  #     - /root/docker/redis-5.0.3/6379:/data
  #   command: redis-server /data/redis.conf

networks:
  app-network:
    driver: bridge
