version: '3.7'

services:
  xsync-bmm-front-development:
    image: node:lts-alpine
    container_name: xsync-bmm-front-development
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      # - API_URL=127.0.0.1:8989
      - API_URL=https://bmm.xsync.info/api
    restart: always
    volumes:
      - .:/usr/src/app
      - app_node_modules:/usr/src/app/node_modules
    ports:
      - '3000:3000'
    command: >
      sh -c 'npm i -g nodemon npm i && npm run dev'
volumes:
  app_node_modules:
