version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: bmm-development
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - API_URL=http://192.168.1.20:8989/api
      - PORT=3001 # 포트 변경할경우 요기랑 밑에 변경해줘야 함.
      # - API_URL=https://bmm.xsync.info/api
    restart: unless-stopped
    networks: 
      - app-network
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - '3001:3001'
    command: npm run dev

volumes:
  node_modules:
networks:
  app-network:
    driver: bridge

