version: '3.4'

services:
  bmm-front:
    image: node:lts-alpine
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
      - API_URL=https://bmm.xsync.info/api
      - HOST=0.0.0.0
    container_name: bmm-front
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    networks:
      - app-network
    command: >
      sh -c 'yarn global add nodemon &&
      yarn && yarn run docker-dev'
networks:
  app-network:
