version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: development
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      # - API_URL=127.0.0.1:8989
      - API_URL=https://bmm.xsync.info/api
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - '3000:3000'
    command: npm run dev

volumes:
  node_modules:
