version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: bmm-dev
    working_dir: /usr/src/app
    environment:
      - API_URL=https://bmm-dev.xsync.info/api
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3000
    restart: unless-stopped
    networks: 
      - app-network
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
volumes:
  node_modules:
networks:
  app-network:
    driver: bridge

