version: "3.7"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: development
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - API_URL=http://0.0.0.0:8989/api
      # - API_URL=https://bmm.xsync.info/api
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - "3000:3001"
    command: yarn run dev

volumes:
  node_modules:
