FROM node:lts-alpine as development
RUN yarn global add pm2
COPY package*.json ./
RUN yarn install
WORKDIR /usr/src/app
COPY . .
CMD [ "pm2-docker", "start", "ecosystem.config.js", "--env=development" ]

